name = "SLTRC"
uuid = "d6fe5f41-4f0c-491c-9521-5e8d2d49c65d"
authors = ["aconitum3 <aconitum@example.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
